-- Baseline: esquema completo da plataforma, extraído da produção a 2026-09-26.
--
-- Substitui as migrações anteriores (arquivadas em supabase/migrations_legacy/),
-- que não reproduziam a base de dados: várias tabelas (demos, historico,
-- viaturas, objetivos_*, infractions, penalties, …) tinham sido criadas fora
-- do repositório e control_records nunca era criada.
--
-- Aplicar num projeto Supabase vazio cria uma instância nova da plataforma.
-- Na produção atual (Baviera) nada tem de ser aplicado: o esquema já é este.
-- Tabelas de outras aplicações que partilham esse projeto (cs_*,
-- exit_targets) e tabelas sem uso (locais, precos_inputs, viaturas_vendidas)
-- ficam de fora.
--
-- Depois de aplicar: inserir o email do primeiro administrador em
-- public.platform_admins e correr supabase/seeds/new_client_defaults.sql.

-- ── Funções ─────────────────────────────────────────────────────────────────
create or replace function public.crm_set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ── Utilizadores e permissões ───────────────────────────────────────────────
create table if not exists public.app_roles (
  name text not null,
  is_admin boolean default false not null,
  permissions jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint app_roles_pkey primary key (name)
);

create table if not exists public.app_users (
  id uuid default gen_random_uuid() not null,
  nome text,
  email text,
  perfil text,
  local jsonb,
  negocio jsonb,
  marca jsonb,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint app_users_email_key unique (email),
  constraint app_users_pkey primary key (id)
);

-- Administradores sem perfil em app_users. Sem políticas: só service role.
create table if not exists public.platform_admins (
  email text not null,
  created_at timestamp with time zone default now() not null,
  constraint platform_admins_pkey primary key (email),
  constraint platform_admins_email_check check (email = lower(email))
);

-- Tabela legada de utilizadores (ainda lida pelo frontend).
create table if not exists public.utilizadores (
  id bigint generated by default as identity not null,
  nome text,
  email text,
  perfil text,
  local jsonb,
  negocio jsonb,
  marca jsonb,
  password text,
  constraint utilizadores_pkey primary key (id)
);

-- ── Registos de controlo (VN / VU) ──────────────────────────────────────────
create table if not exists public.control_records (
  id uuid default gen_random_uuid() not null,
  status text,
  neg date,
  mes1 text,
  resp text,
  cliente text,
  type text,
  biz text,
  enc text,
  chas text,
  mat text,
  model text,
  version text,
  gar text,
  qor numeric default 0,
  xev numeric default 0,
  bev numeric default 0,
  m numeric default 0,
  csc numeric default 0,
  cme numeric,
  fin text,
  week198 text,
  dmat date,
  date298 date,
  app date,
  obs text,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now(),
  id_cliente text,
  mpa numeric default 0,
  gkl numeric default 0,
  dfat date,
  ret smallint default 0 not null,
  constraint control_records_pkey primary key (id)
);

create table if not exists public.control_records_vu (
  id uuid default gen_random_uuid() not null,
  status text,
  neg date,
  mes1 text,
  resp text,
  cliente text,
  type text,
  biz text,
  enc text,
  chas text,
  mat text,
  model text,
  version text,
  gar text,
  qor numeric default 0,
  xev numeric default 0,
  bev numeric default 0,
  m numeric default 0,
  csc numeric default 0,
  cme numeric,
  fin text,
  week198 text,
  dmat date,
  date298 date,
  app date,
  obs text,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now(),
  id_cliente text,
  mpa numeric default 0,
  gkl numeric default 0,
  dfat date,
  ret smallint default 0 not null,
  dt_fecho date,
  prov text,
  a360 integer default 0,
  recond integer default 0,
  dgarant text,
  garant3s text,
  constraint control_records_vu_pkey primary key (id)
);

create table if not exists public.historico (
  id bigint generated always as identity not null,
  tabela text not null,
  acao text not null,
  registo_id text not null,
  detalhes jsonb,
  data_hora timestamp with time zone default now(),
  constraint historico_pkey primary key (id)
);

-- ── CRM fidelização ─────────────────────────────────────────────────────────
create table if not exists public.crm_notes (
  id uuid default gen_random_uuid() not null,
  resp text,
  cliente text,
  control_id uuid,
  body text not null,
  created_by text,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint crm_notes_pkey primary key (id)
);

create table if not exists public.crm_reminders (
  id uuid default gen_random_uuid() not null,
  resp text,
  cliente text,
  control_id uuid,
  kind text default 'geral'::text not null,
  title text not null,
  body text,
  due_at timestamp with time zone,
  done boolean default false not null,
  done_at timestamp with time zone,
  created_by text,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint crm_reminders_pkey primary key (id),
  constraint crm_reminders_kind_check check ((kind = any (array['geral'::text, 'chamada'::text, 'followup'::text, 'renovacao'::text, 'servico'::text])))
);

-- ── Demos ───────────────────────────────────────────────────────────────────
create table if not exists public.demos (
  id uuid default gen_random_uuid() not null,
  local text,
  modelo text,
  versao text,
  enc text,
  chass text,
  mat text,
  data date,
  ice text,
  xev text,
  bev text,
  qor text,
  m text,
  t1 numeric,
  pvb numeric,
  opc numeric,
  bsi text,
  pct numeric,
  eco numeric,
  leg_tr numeric,
  isv numeric,
  pvp numeric,
  mgb numeric,
  esf numeric,
  pac numeric,
  dem numeric,
  sup numeric,
  dsc_eur numeric,
  desc_pct numeric,
  iva2 numeric,
  pv_min numeric,
  t2 numeric,
  dep numeric,
  dep_eur numeric,
  mg numeric,
  pvp_desc numeric,
  s_iva numeric,
  net numeric,
  evento text,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now(),
  constraint demos_pkey primary key (id)
);

create table if not exists public.demo_emprestimos (
  id uuid default gen_random_uuid() not null,
  demo_id uuid not null,
  tipo text not null,
  alocado_nome text not null,
  notas text,
  inicio timestamp with time zone not null,
  fim timestamp with time zone not null,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now(),
  cliente_telefone text,
  cliente_nif text,
  constraint demo_emprestimos_pkey primary key (id),
  constraint demo_emprestimos_periodo_valido check ((fim > inicio)),
  constraint demo_emprestimos_tipo_check check ((tipo = any (array['interno'::text, 'cliente'::text])))
);

create table if not exists public.demo_capas (
  chassis text not null,
  url text not null,
  updated_by text,
  updated_at timestamp with time zone default now() not null,
  constraint demo_capas_pkey primary key (chassis)
);

create table if not exists public.demo_pessoas (
  id uuid default gen_random_uuid() not null,
  nome text not null,
  created_at timestamp with time zone default now() not null,
  constraint demo_pessoas_pkey primary key (id)
);

create table if not exists public.demo_afetacoes (
  chassis text not null,
  pessoa_id uuid not null,
  created_at timestamp with time zone default now() not null,
  constraint demo_afetacoes_pkey primary key (chassis, pessoa_id)
);

create table if not exists public.viaturas (
  chassis text not null,
  matricula text,
  modelo text,
  versao text,
  estado_entrega text,
  data_matricula date,
  encomenda text,
  tipologia jsonb,
  local jsonb,
  link_fotos text,
  inputs jsonb,
  stats jsonb,
  marca text,
  estado_negocio text,
  reserva_expira timestamp with time zone,
  reserva_user text,
  observacoes text,
  kms integer,
  iva_dedutivel boolean default false not null,
  constraint viaturas_pkey primary key (chassis)
);

-- ── Lavagem ─────────────────────────────────────────────────────────────────
create table if not exists public.car_wash_cycles (
  id uuid default gen_random_uuid() not null,
  plate text not null,
  wash_type text not null,
  duration_min integer not null,
  started_at timestamp with time zone,
  ended_at timestamp with time zone,
  created_by text,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  quality_score integer,
  quality_comment text,
  quality_by text,
  quality_at timestamp with time zone,
  scheduled_at timestamp with time zone,
  effective_at timestamp with time zone generated always as (coalesce(started_at, scheduled_at)) stored,
  queue_order double precision,
  model text,
  notes text,
  scheduled_by text,
  constraint car_wash_cycles_pkey primary key (id),
  constraint car_wash_cycles_quality_score_check check (((quality_score >= 0) and (quality_score <= 10))),
  constraint car_wash_cycles_wash_type_check check ((wash_type = any (array['simples'::text, 'oferta'::text, 'completa'::text, 'parque'::text, 'servico'::text, 'novo'::text, 'bps'::text, 'retoma'::text, 'mota_vn'::text, 'mota_vu'::text])))
);

create table if not exists public.car_wash_events (
  id uuid default gen_random_uuid() not null,
  cycle_id uuid,
  action text not null,
  actor text,
  plate text,
  wash_type text,
  detail text,
  snapshot jsonb,
  created_at timestamp with time zone default now() not null,
  constraint car_wash_events_pkey primary key (id),
  constraint car_wash_events_action_check check ((action = any (array['create'::text, 'reschedule'::text, 'queue'::text, 'start'::text, 'end'::text, 'quality'::text, 'delete'::text])))
);

-- ── Qualidade, objetivos, multas ────────────────────────────────────────────
create table if not exists public.quality_scores (
  year integer not null,
  month integer not null,
  retails numeric default 0 not null,
  contratos numeric default 0 not null,
  atitude numeric default 0 not null,
  atendimento numeric default 0 not null,
  assiduidade numeric default 0 not null,
  equipa numeric default 0 not null,
  nps100 numeric default 0 not null,
  updated_by text,
  updated_at timestamp with time zone default now() not null,
  vendedor text default ''::text not null,
  constraint quality_scores_pkey primary key (year, month, vendedor),
  constraint quality_scores_month_check check (((month >= 1) and (month <= 12)))
);

-- NB: tipo 'BMW' é específico do cliente atual (ver parametrização).
create table if not exists public.objetivos_orcamento (
  id uuid default gen_random_uuid() not null,
  ano integer not null,
  mes integer not null,
  tipo text not null,
  orcamento numeric(12,2) default 0 not null,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now(),
  constraint objetivos_orcamento_ano_mes_tipo_key unique (ano, mes, tipo),
  constraint objetivos_orcamento_pkey primary key (id),
  constraint objetivos_orcamento_mes_check check (((mes >= 1) and (mes <= 12))),
  constraint objetivos_orcamento_tipo_check check ((tipo = any (array['GSC'::text, 'BMW'::text])))
);

create table if not exists public.objetivos_resp (
  id uuid default gen_random_uuid() not null,
  ano integer not null,
  mes integer not null,
  responsavel text not null,
  objetivo integer default 0 not null,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now(),
  constraint objetivos_resp_ano_mes_responsavel_key unique (ano, mes, responsavel),
  constraint objetivos_resp_pkey primary key (id),
  constraint objetivos_resp_mes_check check (((mes >= 1) and (mes <= 12)))
);

create table if not exists public.vu_objetivos (
  mes text not null,
  faturas numeric default 0 not null,
  updated_at timestamp with time zone default now() not null,
  constraint vu_objetivos_pkey primary key (mes)
);

create table if not exists public.infractions (
  id uuid default gen_random_uuid() not null,
  name text not null,
  value numeric default 2 not null,
  active boolean default true,
  created_at timestamp with time zone default now(),
  constraint infractions_pkey primary key (id)
);

create table if not exists public.penalty_cycles (
  id integer not null,
  started_at timestamp with time zone default now(),
  ended_at timestamp with time zone,
  notes text,
  constraint penalty_cycles_pkey primary key (id)
);

create table if not exists public.penalties (
  id uuid default gen_random_uuid() not null,
  resp text not null,
  infraction_id uuid,
  infraction_name text not null,
  value numeric not null,
  registered_by text,
  cycle_id integer default 1 not null,
  created_at timestamp with time zone default now(),
  constraint penalties_pkey primary key (id)
);

-- ── Retomas / angariação VU ─────────────────────────────────────────────────
create table if not exists public.retomas (
  id uuid default gen_random_uuid() not null,
  marca text not null,
  modelo text not null,
  motorizacao text,
  matricula text,
  data_matricula date,
  quilometragem integer,
  importado boolean default false not null,
  link_caetano text,
  link_maxterauto text,
  link_fotos text,
  arquivada boolean default false not null,
  arquivada_at timestamp with time zone,
  created_by text,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  data_entrada_stock date default current_date not null,
  preco numeric(10,2),
  observacoes text,
  constraint retomas_pkey primary key (id),
  constraint retomas_motorizacao_check check ((motorizacao = any (array['ice'::text, 'phev'::text, 'bev'::text]))),
  constraint retomas_preco_check check (((preco is null) or (preco >= (0)::numeric))),
  constraint retomas_quilometragem_check check (((quilometragem is null) or (quilometragem >= 0)))
);

create table if not exists public.angariacoes_vu (
  id uuid default gen_random_uuid() not null,
  dt_ang date,
  resp text,
  cliente text,
  angar text,
  mat text,
  model text,
  version text,
  ano integer,
  kms integer,
  v_compra numeric,
  created_at timestamp with time zone default now() not null,
  constraint angariacoes_vu_pkey primary key (id)
);

-- ── End of Term ─────────────────────────────────────────────────────────────
create table if not exists public.eot_contracts (
  contrato text not null,
  concessionario text,
  vendedor text,
  tipo text,
  cliente text,
  contacto text,
  telefone text,
  telemovel text,
  morada text,
  codigo_postal text,
  data_fim date,
  prazo integer,
  prestacao numeric,
  kms_contratados numeric,
  matricula text,
  marca text,
  modelo text,
  seguro text,
  manutencao text,
  manutencao_tipo text,
  valor_residual numeric,
  despesas_finais numeric,
  valor_total numeric,
  concessionario_resp text,
  fase text default 'pendente'::text not null,
  resultado text,
  obs text,
  owner_email text,
  owner_nome text,
  imported_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint eot_contracts_pkey primary key (contrato),
  constraint eot_contracts_fase_check check ((fase = any (array['pendente'::text, 'contactado'::text, 'proposta_enviada'::text, 'negociacao'::text, 'renovado'::text, 'retomado'::text, 'perdido'::text, 'sem_interesse'::text])))
);

create table if not exists public.eot_activities (
  id uuid default gen_random_uuid() not null,
  contrato text not null,
  tipo text default 'chamada'::text not null,
  descricao text,
  due_at timestamp with time zone,
  done boolean default false not null,
  done_at timestamp with time zone,
  autor text,
  owner_email text,
  created_by text,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint eot_activities_pkey primary key (id),
  constraint eot_activities_tipo_check check ((tipo = any (array['chamada'::text, 'email'::text, 'reuniao'::text, 'visita'::text, 'proposta_feita'::text, 'proposta_enviada'::text, 'outro'::text])))
);

-- ── Prospeção ───────────────────────────────────────────────────────────────
create table if not exists public.prospec_accounts (
  id uuid default gen_random_uuid() not null,
  nome text not null,
  setor text,
  potencial integer,
  dimensao_frota integer,
  relacao integer,
  fase text default 'novo'::text not null,
  fonte text,
  owner_email text,
  owner_nome text,
  created_by text,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  score numeric generated always as (round(((((coalesce(potencial, 0))::numeric * 0.5) + ((
    case dimensao_frota
      when 0 then 0
      when 1 then 3
      when 2 then 5
      else 0
    end)::numeric * 0.3)) + ((coalesce(relacao, 0))::numeric * 0.2)), 2)) stored,
  constraint prospec_accounts_pkey primary key (id),
  constraint prospec_accounts_dimensao_frota_check check ((dimensao_frota = any (array[0, 1, 2]))),
  constraint prospec_accounts_fase_check check ((fase = any (array['novo'::text, 'contactado'::text, 'reuniao'::text, 'proposta'::text, 'negociacao'::text, 'ganho'::text, 'perdido'::text]))),
  constraint prospec_accounts_fonte_check check ((fonte = any (array['geografica'::text, 'lookalike'::text, 'indicacao'::text, 'relacao'::text, 'lusha'::text, 'outro'::text]))),
  constraint prospec_accounts_potencial_check check (((potencial >= 1) and (potencial <= 5))),
  constraint prospec_accounts_relacao_check check (((relacao >= 1) and (relacao <= 5)))
);

create table if not exists public.prospec_contacts (
  id uuid default gen_random_uuid() not null,
  account_id uuid not null,
  nome text not null,
  cargo text,
  email text,
  telefone text,
  fonte text,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint prospec_contacts_pkey primary key (id)
);

create table if not exists public.prospec_interactions (
  id uuid default gen_random_uuid() not null,
  account_id uuid not null,
  tipo text default 'chamada'::text not null,
  occurred_at timestamp with time zone default now() not null,
  autor text,
  nota text,
  created_at timestamp with time zone default now() not null,
  constraint prospec_interactions_pkey primary key (id),
  constraint prospec_interactions_tipo_check check ((tipo = any (array['chamada'::text, 'email'::text, 'reuniao'::text, 'visita'::text])))
);

create table if not exists public.prospec_tasks (
  id uuid default gen_random_uuid() not null,
  type text default 'todo'::text not null,
  account_id uuid,
  owner_email text,
  owner_nome text,
  descricao text not null,
  due_at timestamp with time zone,
  done boolean default false not null,
  done_at timestamp with time zone,
  created_by text,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  constraint prospec_tasks_pkey primary key (id),
  constraint prospec_tasks_type_check check ((type = any (array['todo'::text, 'next_action'::text])))
);

-- Web Push (escritas só pelas edge functions, com service role).
create table if not exists public.prospec_push_subs (
  endpoint text not null,
  p256dh text not null,
  auth text not null,
  user_email text,
  ua text,
  last_ok timestamp with time zone,
  fail_count integer default 0 not null,
  created_at timestamp with time zone default now() not null,
  constraint prospec_push_subs_pkey primary key (endpoint)
);

create table if not exists public.prospec_push_sent (
  day_key text not null,
  ref text not null,
  user_email text not null,
  sent_at timestamp with time zone default now() not null,
  constraint prospec_push_sent_pkey primary key (day_key, ref, user_email)
);

-- ── Notificações ────────────────────────────────────────────────────────────
create table if not exists public.notifications (
  id uuid default gen_random_uuid() not null,
  title text not null,
  body text,
  audience text default 'all'::text not null,
  created_by text,
  created_by_nome text,
  created_at timestamp with time zone default now() not null,
  constraint notifications_pkey primary key (id)
);

create table if not exists public.notification_reads (
  notification_id uuid not null,
  user_email text not null,
  read_at timestamp with time zone default now() not null,
  constraint notification_reads_pkey primary key (notification_id, user_email)
);

-- ── Chaves estrangeiras ─────────────────────────────────────────────────────
do $$
declare
  fk record;
begin
  for fk in select * from (values
    ('demo_afetacoes', 'demo_afetacoes_pessoa_id_fkey', 'foreign key (pessoa_id) references public.demo_pessoas(id) on delete cascade'),
    ('demo_emprestimos', 'demo_emprestimos_demo_id_fkey', 'foreign key (demo_id) references public.demos(id) on delete cascade'),
    ('eot_activities', 'eot_activities_contrato_fkey', 'foreign key (contrato) references public.eot_contracts(contrato) on delete cascade'),
    ('notification_reads', 'notification_reads_notification_id_fkey', 'foreign key (notification_id) references public.notifications(id) on delete cascade'),
    ('penalties', 'penalties_infraction_id_fkey', 'foreign key (infraction_id) references public.infractions(id)'),
    ('prospec_contacts', 'prospec_contacts_account_id_fkey', 'foreign key (account_id) references public.prospec_accounts(id) on delete cascade'),
    ('prospec_interactions', 'prospec_interactions_account_id_fkey', 'foreign key (account_id) references public.prospec_accounts(id) on delete cascade'),
    ('prospec_tasks', 'prospec_tasks_account_id_fkey', 'foreign key (account_id) references public.prospec_accounts(id) on delete cascade')
  ) as v(tbl, name, def) loop
    if not exists (select 1 from pg_constraint where conname = fk.name) then
      execute format('alter table public.%I add constraint %I %s', fk.tbl, fk.name, fk.def);
    end if;
  end loop;
end $$;

-- ── Índices ─────────────────────────────────────────────────────────────────
create index if not exists car_wash_cycles_effective_idx on public.car_wash_cycles (effective_at);
create index if not exists car_wash_cycles_open_idx on public.car_wash_cycles (ended_at);
create index if not exists car_wash_cycles_plate_idx on public.car_wash_cycles (plate);
create index if not exists car_wash_cycles_scheduled_idx on public.car_wash_cycles (scheduled_at);
create index if not exists car_wash_cycles_started_idx on public.car_wash_cycles (started_at);
create index if not exists car_wash_events_created_idx on public.car_wash_events (created_at);
create index if not exists car_wash_events_cycle_idx on public.car_wash_events (cycle_id);
create index if not exists crm_notes_cliente_idx on public.crm_notes (cliente);
create index if not exists crm_notes_control_idx on public.crm_notes (control_id);
create index if not exists crm_notes_resp_idx on public.crm_notes (resp);
create index if not exists crm_reminders_control_idx on public.crm_reminders (control_id);
create index if not exists crm_reminders_due_idx on public.crm_reminders (due_at);
create index if not exists crm_reminders_open_idx on public.crm_reminders (done, due_at);
create index if not exists crm_reminders_resp_idx on public.crm_reminders (resp);
create index if not exists demo_afetacoes_chassis_idx on public.demo_afetacoes (chassis);
create index if not exists demo_emprestimos_demo_id_idx on public.demo_emprestimos (demo_id);
create index if not exists demo_emprestimos_periodo_idx on public.demo_emprestimos (inicio, fim);
create index if not exists eot_activities_contrato_idx on public.eot_activities (contrato, created_at desc);
create index if not exists eot_activities_open_idx on public.eot_activities (done, due_at);
create index if not exists eot_activities_owner_idx on public.eot_activities (owner_email);
create index if not exists eot_contracts_data_fim_idx on public.eot_contracts (data_fim);
create index if not exists eot_contracts_fase_idx on public.eot_contracts (fase);
create index if not exists eot_contracts_owner_idx on public.eot_contracts (owner_email);
create index if not exists eot_contracts_vendedor_idx on public.eot_contracts (vendedor);
create index if not exists notifications_created_at_idx on public.notifications (created_at desc);
create index if not exists prospec_accounts_fase_idx on public.prospec_accounts (fase);
create index if not exists prospec_accounts_owner_idx on public.prospec_accounts (owner_email);
create index if not exists prospec_accounts_score_idx on public.prospec_accounts (score);
create index if not exists prospec_contacts_account_idx on public.prospec_contacts (account_id);
create index if not exists prospec_interactions_account_idx on public.prospec_interactions (account_id, occurred_at desc);
create index if not exists prospec_push_subs_email_idx on public.prospec_push_subs (lower(user_email));
create index if not exists prospec_tasks_account_idx on public.prospec_tasks (account_id);
create index if not exists prospec_tasks_open_idx on public.prospec_tasks (done, due_at);
create index if not exists prospec_tasks_owner_idx on public.prospec_tasks (owner_email);
create index if not exists prospec_tasks_type_idx on public.prospec_tasks (type);
create index if not exists retomas_arquivada_idx on public.retomas (arquivada);
create index if not exists retomas_created_idx on public.retomas (created_at desc);
create index if not exists retomas_entrada_idx on public.retomas (data_entrada_stock);
create index if not exists retomas_matricula_idx on public.retomas (matricula);

-- ── Triggers updated_at ─────────────────────────────────────────────────────
do $$
declare
  t text;
begin
  foreach t in array array[
    'app_roles', 'app_users', 'car_wash_cycles', 'crm_notes', 'crm_reminders',
    'eot_activities', 'eot_contracts', 'prospec_accounts', 'prospec_contacts',
    'prospec_tasks', 'quality_scores', 'retomas'
  ] loop
    execute format('drop trigger if exists %I on public.%I', t || '_updated_at', t);
    execute format(
      'create trigger %I before update on public.%I for each row execute function public.crm_set_updated_at()',
      t || '_updated_at', t);
  end loop;
end $$;

-- ── Acesso: só utilizadores da plataforma ───────────────────────────────────
-- Utilizador da plataforma = email em app_users ou em platform_admins.
create or replace function public.is_platform_user()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(
    exists (
      select 1 from public.app_users a
      where lower(a.email) = lower(auth.jwt() ->> 'email')
    ) or exists (
      select 1 from public.platform_admins p
      where p.email = lower(auth.jwt() ->> 'email')
    ),
    false
  );
$$;

revoke all on function public.is_platform_user() from public, anon;
grant execute on function public.is_platform_user() to authenticated;

do $$
declare
  t text;
  p record;
  rw_tables text[] := array[
    'angariacoes_vu', 'car_wash_cycles', 'car_wash_events',
    'control_records', 'control_records_vu', 'crm_notes', 'crm_reminders',
    'demo_afetacoes', 'demo_capas', 'demo_emprestimos', 'demo_pessoas', 'demos',
    'eot_activities', 'eot_contracts', 'historico', 'infractions',
    'notification_reads', 'notifications', 'objetivos_orcamento',
    'objetivos_resp', 'penalties', 'penalty_cycles', 'prospec_accounts',
    'prospec_contacts', 'prospec_interactions', 'prospec_tasks',
    'quality_scores', 'retomas', 'utilizadores', 'viaturas', 'vu_objetivos'
  ];
  -- Escritas só pela edge function admin-users (service role).
  ro_tables text[] := array['app_users', 'app_roles'];
  -- Sem políticas: só service role.
  locked_tables text[] := array['platform_admins', 'prospec_push_subs', 'prospec_push_sent'];
begin
  foreach t in array rw_tables || ro_tables || locked_tables loop
    execute format('alter table public.%I enable row level security', t);
    for p in select policyname from pg_policies
             where schemaname = 'public' and tablename = t loop
      execute format('drop policy %I on public.%I', p.policyname, t);
    end loop;
    if t = any(ro_tables) then
      execute format(
        'create policy platform_users_read on public.%I for select to authenticated using (public.is_platform_user())', t);
    elsif t = any(rw_tables) then
      execute format(
        'create policy platform_users on public.%I for all to authenticated using (public.is_platform_user()) with check (public.is_platform_user())', t);
    end if;
  end loop;
end $$;

-- ── Storage ─────────────────────────────────────────────────────────────────
insert into storage.buckets (id, name, public)
values ('excel-files', 'excel-files', false), ('demo-capas', 'demo-capas', true)
on conflict (id) do update set public = excluded.public;

drop policy if exists excel_files_select on storage.objects;
drop policy if exists excel_files_insert on storage.objects;
drop policy if exists excel_files_update on storage.objects;
drop policy if exists excel_files_delete on storage.objects;
drop policy if exists demo_capas_obj_read on storage.objects;
drop policy if exists demo_capas_obj_insert on storage.objects;
drop policy if exists demo_capas_obj_update on storage.objects;
drop policy if exists demo_capas_obj_delete on storage.objects;

-- excel-files: privado, só utilizadores da plataforma.
create policy excel_files_select on storage.objects
  for select to authenticated
  using (bucket_id = 'excel-files' and public.is_platform_user());
create policy excel_files_insert on storage.objects
  for insert to authenticated
  with check (bucket_id = 'excel-files' and public.is_platform_user());
create policy excel_files_update on storage.objects
  for update to authenticated
  using (bucket_id = 'excel-files' and public.is_platform_user())
  with check (bucket_id = 'excel-files' and public.is_platform_user());
create policy excel_files_delete on storage.objects
  for delete to authenticated
  using (bucket_id = 'excel-files' and public.is_platform_user());

-- demo-capas: imagens públicas (getPublicUrl), escrita restrita.
create policy demo_capas_obj_read on storage.objects
  for select using (bucket_id = 'demo-capas');
create policy demo_capas_obj_insert on storage.objects
  for insert to authenticated
  with check (bucket_id = 'demo-capas' and public.is_platform_user());
create policy demo_capas_obj_update on storage.objects
  for update to authenticated
  using (bucket_id = 'demo-capas' and public.is_platform_user())
  with check (bucket_id = 'demo-capas' and public.is_platform_user());
create policy demo_capas_obj_delete on storage.objects
  for delete to authenticated
  using (bucket_id = 'demo-capas' and public.is_platform_user());
